apiVersion: v1
kind: Namespace
metadata:
  name: sidecar-injector
spec: {}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-role
rules:
- apiGroups:
  - k8s.crd.io
  - apps
  - ""
  resources:
  - policydefinitions
  - pods
  - pods/log
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: sidecar-injector

