apiVersion: sampleproject.io/v1alpha1
kind: Receiver
metadata:
  name: myreceiver1
  labels:
    target: server
    key: value1
spec:
  Namespace:
    - default
  labelSelector:
    matchExpression:
      - {key: app, operator: in, values: ['title-api']}
      - {key: version, operator: in, values: ['v1', 'v3']}
  action: quarantine
  groupLabel: [app]
  logFrequency: 30
  destination:
    - ipaddress: "192.168.0.9"
      port: "3000"
      endpoint: "/"
