apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector-webhook.rohit.in
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01EVXhNekV3TlRjeU1Gb1hEVE13TURVeE1qRXdOVGN5TUZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTG5jCndqMUloWFJYMXRJS0t1a3pBaEhYYXJUd2QzbysxelNLWDVNdWZzSEhLQlRyeUkwbXM4UDMwcWxTcXUrNzlIS1cKZGtLMjZmWHJOUTMvM2xSNXlVeDJZcUs3eWp5SHpWNUdBaGJqSXU5MTBhSnBKU0JUS0tXNlVhKzdlTTB1bzlrQgplZEd3L3JlQTIxb00zc2NXb3BFN3NhbWVqdFQwdFQrRVNuek52OUVtQ2h1dWgvWGxoaVJhWkdwVkQ3U0MrK0FOCjQvdlhOQ3VicDVTL0ZvL3kzUUVNa0llS0tHekx4MllrWk03Unh4SGc4OFFZVVhHQmFQUnB2OVBDRDBVTENVOG4KQW1QTmtaQUhYQVRiTXlORk1hVy9kYW9aK1hJTlgvdytQUlBkM0tqQ0xjQTc1M3VMRHJxcWpkUzB1OVl5cFlNeQpvbFZRSzRTNS81YXVraVZGWExrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDb0Zsc1U0NmIwWUVJd1N6K2RiOFJDNzRkZ2ZPRUZWczlsNC94bkN5K2dlaEgxWHhNWgpMTHBrbFM1U0dVb1RmK215U29UNjlaRFpYcHBBdm94RVZXdFJscGhSNUhHSUVPV1Z6SGtXdGVvMWM4K3ZkcEFyCmIvN2ZQYlB1ZVQxV1BkcmJkMnNoTU9ncmZpY3dlZnFsNS94Mm1TUHdpa25lc3M2UkFoNUhkaHFnV1lLbkQ4dTIKaHlXcDYvc3h0TUpIaENMRHdqTFN1ZkJack40OVJYWE01VVUvcWlYelV6ZmtmeTRxU1RCc3cwWlBhOSt6V0ZlNQpKaEdmejkrNjFvZXhNSWZKMHRGTGpGTTBmSGFpVWpreXg4LzZuRmx2OGRyUzF4cUJuNlAyT2RjQnZjNkd0RURSCjBJQTBtbThCalc1TVQyamtodmFMNDh0VFJpZUNrT0JtVVR1NgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
